### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by ivanvoid** [nifunk/learning_event_triggered_control#1]
Hi tried to run your code, got error. Seems like you just can't set this attribute, but in your code you do that???
any feedback, will be welcome 
```
python run_retrain.py --opt 2 --seed 0 --app savename --epoch 500 --path=PATH_TO_RESULTS_FOLDER --env Pendulumnf-v0
/home/ivan/miniconda3/envs/tf36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ivan/miniconda3/envs/tf36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ivan/miniconda3/envs/tf36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ivan/miniconda3/envs/tf36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:472: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ivan/miniconda3/envs/tf36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:473: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ivan/miniconda3/envs/tf36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:476: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/ivan/miniconda3/envs/tf36/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
2023-02-28 17:38:22.746760: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
['/home/ivan/Projects/reacher_etc/data/learning_event_triggered_control/retrain_proc', '/home/ivan/miniconda3/envs/tf36/lib/python36.zip', '/home/ivan/miniconda3/envs/tf36/lib/python3.6', '/home/ivan/miniconda3/envs/tf36/lib/python3.6/lib-dynload', '/home/ivan/miniconda3/envs/tf36/lib/python3.6/site-packages', '../baselines', '../pretrained_models/1_Pendulum/0_5', '../', '/home/nfunk/Code_MA/nn_veri/Marabou', 'PATH_TO_RESULTS_FOLDER']
/home/ivan/miniconda3/envs/tf36/lib/python3.6/site-packages/gym/spaces/box.py:74: UserWarning: WARN: Box bound precision lowered by casting to float32
  "Box bound precision lowered by casting to {}".format(self.dtype)
Traceback (most recent call last):
  File "run_retrain.py", line 108, in <module>
    main()
  File "run_retrain.py", line 104, in main
    epoch=args.epoch,dc=args.dc,path=args.path,render=args.render,official=args.official,orig_ppo=args.orig_ppo)
  File "run_retrain.py", line 80, in train
    path=path
  File "../retrain_proc/retrain.py", line 229, in learn
    ob_space.shape =((ob_space.shape[0] + ac_space.shape[0]),)
AttributeError: can't set attribute
```

**Comment by nifunk** [comment]
Hi,

First of all, sorry for my late response, but I have been working towards a deadline that is why only now I found the time to look into it.

That said, so far, I was not able to reproduce the specific error you reported. One thing that I noticed was that you were not giving a path to a model from where the verification would start, as you basically passed "--path=PATH_TO_RESULTS_FOLDER" as an argument in the command above.

However, as I also noticed that getting Marabou to work (and the other things as well, as the dependencies are quite old nowadays), I decided to create a new branch, called "retrain_23" (see https://github.com/nifunk/learning_event_triggered_control/tree/retrain_23).

If you follow the steps of the README on the branch, you should be able to execute the following command without any errors:

python3 run_retrain.py --opt 2 --seed 0 --app savename --epoch 0 --path=PATH_TO_REPO/learning_event_triggered_control/pretrained_models/4_Stability_Verification/retraining/ --env Pendulumnf-v0

(this command was taken from the adapted instructions inside the retrain_proc folder).

I hope this helps!

Cheers
